name: GitHub Profile Activity

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate profile cards
      - name: Generate profile cards
        uses: seijikohara/profile-cards-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: mishrashivamcg-wq
          cards: overview,contributions,languages
          output-dir: assets
          themes: light,dark
          commit: false

      # Generate contribution snake
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github: mishrashivamcg-wq
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit everything
      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets
          git diff --cached --quiet || git commit -m "Update GitHub profile activity"
          git push
